// word-list.js
const wordLevels = {
  3: [
    { en: "information", jp: "情報", similar: ["知識", "内容", "知らせ"] },
    { en: "advice", jp: "助言", similar: ["提案", "ヒント", "忠告"] },
    { en: "environment", jp: "環境", similar: ["自然", "周囲", "状況"] },
    { en: "experience", jp: "経験", similar: ["体験", "練習", "経歴"] },
    { en: "opportunity", jp: "機会", similar: ["チャンス", "時期", "可能性"] },
    { en: "reason", jp: "理由", similar: ["原因", "根拠", "目的"] },
    { en: "purpose", jp: "目的", similar: ["目標", "意図", "理由"] },
    { en: "opinion", jp: "意見", similar: ["考え", "見解", "信念"] },
    { en: "condition", jp: "状態", similar: ["状況", "健康", "条件"] },
    { en: "message", jp: "伝言", similar: ["知らせ", "連絡", "手紙"] },
    { en: "experience", jp: "経験", similar: ["技術", "活動", "習慣"] },
    { en: "environment", jp: "環境", similar: ["自然", "周囲", "状況"] },
    { en: "opportunity", jp: "機会", similar: ["運命", "目的", "可能性"] },
    { en: "improve", jp: "上達させる", similar: ["準備する", "練習する", "発見する"] },
    { en: "opinion", jp: "意見", similar: ["考え", "理想", "理由"] },
    { en: "necessary", jp: "必要な", similar: ["重要な", "便利な", "正確な"] },
    { en: "culture", jp: "文化", similar: ["歴史", "伝統", "社会"] },
    { en: "discover", jp: "発見する", similar: ["発明する", "調査する", "理解する"] },
    { en: "future", jp: "将来", similar: ["過去", "現在", "期待"] },
    { en: "agree", jp: "賛成する", similar: ["反対する", "提案する", "決定する"] },
    { en: "foreign", jp: "外国の", similar: ["遠い", "珍しい", "国際的な"] },
    { en: "prepare", jp: "準備する", similar: ["計画する", "整理する", "修理する"] },
    { en: "successful", jp: "成功した", similar: ["有名な", "幸運な", "満足な"] },
    { en: "careful", jp: "注意深い", similar: ["親切な", "安全な", "真面目な"] },
    { en: "arrive", jp: "到着する", similar: ["出発する", "離れる", "戻る"] },
    { en: "believe", jp: "信じる", similar: ["疑う", "確信させる", "期待する"] },
    { en: "instead", jp: "代わりに", similar: ["特に", "実際に", "突然に"] },
    { en: "popular", jp: "人気のある", similar: ["有名な", "一般的な", "伝統的な"] },
    { en: "medicine", jp: "薬", similar: ["病気", "病院", "治療"] },
    { en: "actually", jp: "実際は", similar: ["おそらく", "絶えず", "ついに"] },
    { en: "government", jp: "政府", similar: ["法律", "国家", "政治"] },
    { en: "education", jp: "教育", similar: ["学習", "訓練", "知識"] },
    { en: "skill", jp: "技術", similar: ["能力", "才能", "経験"] },
    { en: "customer", jp: "客", similar: ["利用者", "訪問者", "買い手"] },
    { en: "neighborhood", jp: "近所", similar: ["地域", "地元", "周辺"] },
    { en: "decision", jp: "決定", similar: ["選択", "判断", "解決"] },
    { en: "pollution", jp: "汚染", similar: ["ゴミ", "被害", "環境破壊"] },
    { en: "product", jp: "製品", similar: ["材料", "作品", "道具"] },
    { en: "suggestion", jp: "提案", similar: ["助言", "計画", "意見"] },
    { en: "local", jp: "地元の", similar: ["田舎の", "近くの", "公共の"] },
    { en: "international", jp: "国際的な", similar: ["外国の", "世界的な", "広い"] },
    { en: "natural", jp: "自然な", similar: ["普通の", "野生の", "元の"] },
    { en: "scared", jp: "怖がって", similar: ["驚いて", "心配して", "怒って"] },
    { en: "useful", jp: "役に立つ", similar: ["便利な", "重要な", "必要な"] },
    { en: "surprised", jp: "驚いた", similar: ["喜んだ", "興奮した", "悲しんだ"] },
    { en: "introduce", jp: "紹介する", similar: ["説明する", "招待する", "見せる"] },
    { en: "support", jp: "支持する", similar: ["手伝う", "守る", "励ます"] },
    { en: "understand", jp: "理解する", similar: ["覚える", "考える", "気づく"] },
    { en: "continue", jp: "続ける", similar: ["始める", "繰り返す", "守る"] },
    { en: "remember", jp: "覚えている", similar: ["忘れる", "思い出す", "記録する"] }


  ],
  pre2: [
    { en: "communicate", jp: "伝える", similar: ["共有する", "やりとりする", "表現する"] },
    { en: "improve", jp: "向上させる", similar: ["改善する", "高める", "進歩させる"] },
    { en: "situation", jp: "状況", similar: ["状態", "事情", "立場"] },
    { en: "opinion", jp: "意見", similar: ["考え", "見解", "主張"] },
    { en: "environment", jp: "環境", similar: ["周囲", "条件", "自然"] },
    { en: "technology", jp: "技術", similar: ["技能", "手法", "方法"] },
    { en: "relationship", jp: "関係", similar: ["つながり", "結びつき", "関連"] },
    { en: "suggest", jp: "提案する", similar: ["勧める", "示す", "申し出る"] },
    { en: "consider", jp: "考慮する", similar: ["検討する", "判断する", "思案する"] },
    { en: "increase", jp: "増える", similar: ["上昇する", "拡大する", "多くなる"] },
    { en: "develop", kana: "ディベロップ", jp: "発展させる", similar: ["成長させる", "開発する", "進展させる"] },
    { en: "reduce", kana: "リデュース", jp: "減らす", similar: ["削減する", "少なくする", "縮小する"] },
    { en: "produce", kana: "プロデュース", jp: "生産する", similar: ["製造する", "作り出す", "産出する"] },
    { en: "available", kana: "アベイラブル", jp: "利用できる", similar: ["入手可能な", "手に入る", "使用可能な"] },
    { en: "local", kana: "ローカル", jp: "地元の", similar: ["地域の", "地方の", "その土地の"] },
    { en: "international", kana: "インターナショナル", jp: "国際的な", similar: ["世界的な", "多国間の", "海外の"] },
    { en: "government", kana: "ガバメント", jp: "政府", similar: ["政権", "行政", "当局"] },
    { en: "society", kana: "ソサエティ", jp: "社会", similar: ["世の中", "共同体", "世間"] },
    { en: "culture", kana: "カルチャー", jp: "文化", similar: ["伝統", "文明", "生活様式"] },
    { en: "history", kana: "ヒストリー", jp: "歴史", similar: ["過去", "沿革", "来歴"] },
    { en: "experience", kana: "エクスペリエンス", jp: "経験", similar: ["体験", "実績", "見聞"] },
    { en: "knowledge", kana: "ナレッジ", jp: "知識", similar: ["知恵", "情報", "理解"] },
    { en: "information", kana: "インフォメーション", jp: "情報", similar: ["知らせ", "データ", "案内"] },
    { en: "future", kana: "フューチャー", jp: "未来", similar: ["将来", "先行き", "今後"] },
    { en: "past", kana: "パスト", jp: "過去", similar: ["以前", "昔", "これまで"] },
    { en: "present", kana: "プレゼント", jp: "現在", similar: ["今", "現状", "当面"] },
    { en: "danger", kana: "デンジャー", jp: "危険", similar: ["リスク", "危機", "脅威"] },
    { en: "safety", kana: "セーフティ", jp: "安全", similar: ["無事", "安心", "保護"] },
    { en: "health", kana: "ヘルス", jp: "健康", similar: ["体調", "健全", "元気"] },
    { en: "energy", kana: "エナジー", jp: "エネルギー", similar: ["活力", "力", "動力"] },
    { en: "population", kana: "ポピュレーション", jp: "人口", similar: ["住民数", "人々", "市民"] },
    { en: "education", kana: "エデュケーション", jp: "教育", similar: ["指導", "学習", "育成"] },
    { en: "industry", kana: "インダストリー", jp: "産業", similar: ["工業", "事業", "業界"] },
    { en: "economy", kana: "エコノミー", jp: "経済", similar: ["財政", "景気", "経営"] },
    { en: "company", kana: "カンパニー", jp: "会社", similar: ["企業", "法人", "事務所"] },
    { en: "employee", kana: "エンプロイー", jp: "従業員", similar: ["社員", "労働者", "職員"] },
    { en: "customer", kana: "カスタマー", jp: "客", similar: ["顧客", "利用者", "買い手"] },
    { en: "service", kana: "サービス", jp: "サービス", similar: ["接客", "奉仕", "業務"] },
    { en: "project", kana: "プロジェクト", jp: "計画", similar: ["企画", "事業", "計画案"] },
    { en: "result", kana: "リザルト", jp: "結果", similar: ["成果", "結末", "成績"] },
    { en: "reason", kana: "リーズン", jp: "理由", similar: ["原因", "根拠", "動機"] },
    { en: "effect", kana: "エフェクト", jp: "影響", similar: ["効果", "作用", "結果"] },
    { en: "purpose", kana: "パーパス", jp: "目的", similar: ["目標", "意図", "狙い"] },
    { en: "role", kana: "ロール", jp: "役割", similar: ["任務", "機能", "立場"] },
    { en: "skill", kana: "スキル", jp: "技能", similar: ["能力", "技術", "腕前"] },
    { en: "ability", kana: "アビリティ", jp: "能力", similar: ["才能", "力量", "技能"] },
    { en: "effort", kana: "エフォート", jp: "努力", similar: ["奮闘", "尽力", "試み"] },
    { en: "success", kana: "サクセス", jp: "成功", similar: ["達成", "勝利", "成果"] },
    { en: "failure", kana: "フェイリャー", jp: "失敗", similar: ["不成功", "敗北", "挫折"] },
    { en: "opportunity", kana: "オポチュニティ", jp: "機会", similar: ["チャンス", "好機", "機運"] },
    { en: "decision", kana: "ディシジョン", jp: "決定", similar: ["判断", "選択", "結論"] },
    { en: "choice", kana: "チョイス", jp: "選択", similar: ["決断", "選定", "選び"] },
    { en: "agreement", kana: "アグリーメント", jp: "同意", similar: ["合意", "承諾", "一致"] },
    { en: "discussion", kana: "ディスカッション", jp: "議論", similar: ["討論", "話し合い", "協議"] },
    { en: "report", kana: "リポート", jp: "報告", similar: ["報道", "記録", "発表"] },
    { en: "research", kana: "リサーチ", jp: "研究", similar: ["調査", "分析", "探究"] },
    { en: "traffic", kana: "トラフィック", jp: "交通", similar: ["往来", "通行", "輸送"] },   
    { en: "transportation", kana: "トランスポーテーション", jp: "輸送", similar: ["運搬", "交通手段", "移送"] },
    { en: "pollution", kana: "ポリューション", jp: "公害", similar: ["汚染", "環境汚染", "大気汚染"] },
    { en: "nature", kana: "ネイチャー", jp: "自然", similar: ["天然", "環境", "本質"] }
  ]
};
